Create table if not exists FUNCIONARIO(
	id INTEGER PRIMARY KEY,
	nome VARCHAR(80) NOT NULL check (LENGTH(nome) >= 10),
	nascimento DATE check(nascimento <= '2002-12-31'),
	CPF VARCHAR(200) NOT NULL UNIQUE
);

Create table if not exists CARGO(
	id INTEGER PRIMARY KEY,
	nome VARCHAR(80) NOT NULL UNIQUE, 
	descricao VARCHAR(80) NOT NULL
);

Create table if not exists DEPARTAMENTO(
	id INTEGER PRIMARY KEY,
	nome VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE IF NOT exists TRABALHA(
	DEPARTAMENTO_id INTEGER NOT NULL REFERENCES DEPARTAMENTO,
	FUNCIONARIO_id INTEGER NOT NULL REFERENCES FUNCIONARIO,
	CARGO_id INTEGER NOT NULL REFERENCES CARGO,
	inicio DATE check (inicio < fim OR fim IS NULL),
	fim DATE,
	PRIMARY KEY(DEPARTAMENTO_id,FUNCIONARIO_id)
);